version: '2'
services:
  db:
    container_name: neo4j
    restart: always
    image: neo4j:3.4.9
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./data:/data"
    environment:
      NEO4J_AUTH: none