version: '2'
services:
  db:
    container_name: postgresql
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: root