dockerhost-web:
  build: docker/
  ports:
    - 9991:80
  volumes:
    - ./public_html:/var/www/html
  container_name: dockerhost_web
  links:
    - dockerhost-db:db

dockerhost-db:
  image: mysql/mysql-server:5.5
  container_name: dockerhost_mysql
  ports:
    - 33991:3306
  volumes:
    - ./docker/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456

dockerhost-pma:
  image: phpmyadmin/phpmyadmin
  ports:
    - 32991:80
  container_name: dockerhost_phpmyadmin
  links:
    - dockerhost-db:db
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 123456