version: '2'
services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/user:/root"
    environment:
      MYSQL_ROOT_PASSWORD: root